import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    slug: "premium-cutting-foam-pad",
    name: "Premium Cutting Foam Pad",
    price: 29.95,
    originalPrice: undefined,
    rating: 4.8,
    reviewCount: 127,
    category: "foam-pads",
    brand: "Masterwolf",
    sku: "MW-FP-001",
    inStock: true,
    stockCount: 84,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Professional-grade cutting foam pad engineered for maximum paint correction. The open-cell foam structure aggressively removes swirls, scratches, and oxidation while maintaining product control and reducing heat buildup.",
    specifications: {
      Size: "150mm (6 inch)",
      Material: "Open-cell polyurethane foam",
      "Backing Plate": "Velcro hook-and-loop",
      "Cut Level": "Heavy cut",
      Compatible: "DA & Rotary polishers",
      Colour: "Orange",
    },
    tags: ["foam pad", "cutting pad", "paint correction", "detailing"],
    featured: true,
  },
  {
    id: "2",
    slug: "ultra-soft-finishing-pad",
    name: "Ultra Soft Finishing Pad",
    price: 24.95,
    originalPrice: undefined,
    rating: 4.9,
    reviewCount: 98,
    category: "foam-pads",
    brand: "Masterwolf",
    sku: "MW-FP-002",
    inStock: true,
    stockCount: 120,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Achieve a flawless, swirl-free finish with our ultra-soft finishing pad. Perfect for applying LSPs, glazes, and fine polishes to produce that deep, mirror-like shine professionals demand.",
    specifications: {
      Size: "150mm (6 inch)",
      Material: "Closed-cell microfibre foam",
      "Backing Plate": "Velcro hook-and-loop",
      "Cut Level": "Finishing / zero cut",
      Compatible: "DA polishers",
      Colour: "White",
    },
    tags: ["foam pad", "finishing pad", "polishing", "detailing"],
    featured: true,
  },
  {
    id: "3",
    slug: "professional-rotary-buffer",
    name: "Professional Rotary Buffer",
    price: 289.0,
    originalPrice: 349.0,
    rating: 4.7,
    reviewCount: 64,
    category: "polishers",
    brand: "Masterwolf",
    sku: "MW-POL-001",
    inStock: true,
    stockCount: 18,
    images: [
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Heavy-duty rotary buffer built for professional paint correction and restoration. Features variable speed control, ergonomic grip, and a brushless motor for consistent, high-torque performance on all surface types.",
    specifications: {
      Power: "1200W",
      "Speed Range": "600–3200 RPM",
      "Pad Size": "150–180mm",
      Weight: "2.1kg",
      Cord: "5m power cord",
      "Chuck Size": "M14 thread",
    },
    tags: ["rotary buffer", "polisher", "paint correction", "professional"],
    featured: true,
  },
  {
    id: "4",
    slug: "dual-action-polisher-pro",
    name: "Dual Action Polisher Pro",
    price: 349.0,
    originalPrice: undefined,
    rating: 4.9,
    reviewCount: 211,
    category: "polishers",
    brand: "Masterwolf",
    sku: "MW-POL-002",
    inStock: true,
    stockCount: 32,
    images: [
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "The industry-leading dual action random orbital polisher. Safe for beginners yet powerful enough for professionals, the DA Pro delivers exceptional results with minimal risk of paint damage.",
    specifications: {
      Power: "900W",
      "Orbit Size": "21mm",
      "Speed Range": "3000–6000 OPM",
      "Pad Size": "150mm",
      Weight: "1.8kg",
      Cord: "5m power cord",
    },
    tags: ["DA polisher", "dual action", "polishing", "professional"],
    featured: true,
  },
  {
    id: "5",
    slug: "premium-microfibre-cloth-pack",
    name: "Premium Microfibre Cloth Pack (10)",
    price: 34.95,
    originalPrice: undefined,
    rating: 4.8,
    reviewCount: 342,
    category: "microfibre",
    brand: "Masterwolf",
    sku: "MW-MF-001",
    inStock: true,
    stockCount: 250,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&q=80",
    ],
    description:
      "Professional-grade 400gsm microfibre cloths that are ultra-soft and scratch-free. Perfect for applying waxes, polishes, and sealants, or for final wipe-down after decontamination.",
    specifications: {
      Pack: "10 cloths",
      GSM: "400gsm",
      Size: "40cm × 40cm",
      Material: "80/20 polyester/polyamide blend",
      Edging: "Silk-banded edge (no scratching)",
      Washing: "Machine washable up to 60°C",
    },
    tags: ["microfibre", "cloths", "wax applicator", "detailing"],
    featured: true,
  },
  {
    id: "6",
    slug: "clay-decontamination-mitt",
    name: "Clay Decontamination Mitt",
    price: 44.95,
    originalPrice: 54.95,
    rating: 4.7,
    reviewCount: 89,
    category: "clay-mitts",
    brand: "Masterwolf",
    sku: "MW-CM-001",
    inStock: true,
    stockCount: 67,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Replace traditional clay bars with this innovative decontamination mitt. The synthetic clay surface safely removes bonded contamination, iron particles, and industrial fallout in a fraction of the time.",
    specifications: {
      Material: "Synthetic clay composite",
      Grade: "Medium grade",
      "Mitt Size": "One size fits most",
      Coverage: "Full vehicle per use (with lubrication)",
      Compatible: "All clear-coat finishes",
      Reusable: "Yes – rinse and store",
    },
    tags: ["clay mitt", "decontamination", "paint prep", "detailing"],
    featured: true,
  },
  {
    id: "7",
    slug: "heavy-cut-compound-500ml",
    name: "Heavy Cut Compound 500ml",
    price: 39.95,
    originalPrice: undefined,
    rating: 4.6,
    reviewCount: 76,
    category: "compounds",
    brand: "Masterwolf",
    sku: "MW-CP-001",
    inStock: true,
    stockCount: 93,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Aggressive cutting compound designed to rapidly remove deep scratches, heavy oxidation, and severe paint defects. Fast-cutting formula leaves a clean, refined surface ready for polishing.",
    specifications: {
      Volume: "500ml",
      Type: "Water-based compound",
      "Cut Level": "Heavy cut",
      "Diminishing Abrasive": "Yes",
      Compatible: "DA & Rotary polishers",
      "Pad Type": "Cutting foam or microfibre",
    },
    tags: ["compound", "cutting compound", "paint correction", "scratch removal"],
    featured: false,
  },
  {
    id: "8",
    slug: "fine-polish-500ml",
    name: "Fine Polish 500ml",
    price: 36.95,
    originalPrice: undefined,
    rating: 4.8,
    reviewCount: 112,
    category: "polishes",
    brand: "Masterwolf",
    sku: "MW-PL-001",
    inStock: true,
    stockCount: 78,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "One-step fine polish that refines and restores paint clarity, eliminating swirl marks, light scratches, and holograms. Suitable for all paint types including sensitive single-stage finishes.",
    specifications: {
      Volume: "500ml",
      Type: "Water-based fine polish",
      "Cut Level": "Light to medium",
      "Diminishing Abrasive": "Yes",
      Compatible: "DA polishers & by hand",
      "Pad Type": "Polishing or finishing pad",
    },
    tags: ["polish", "fine polish", "swirl removal", "paint refinement"],
    featured: false,
  },
  {
    id: "9",
    slug: "detailing-spray-wax-500ml",
    name: "Detailing Spray Wax 500ml",
    price: 29.95,
    originalPrice: undefined,
    rating: 4.7,
    reviewCount: 154,
    category: "waxes",
    brand: "Masterwolf",
    sku: "MW-WX-001",
    inStock: true,
    stockCount: 142,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Quick-detailer spray wax that adds a layer of protection and intense gloss in minutes. Ideal for between-wash maintenance or as a finishing touch after polishing.",
    specifications: {
      Volume: "500ml",
      Type: "Carnauba spray wax blend",
      Application: "Spray and wipe",
      Durability: "4–6 weeks",
      Compatible: "Painted surfaces, glass, plastic",
      Finish: "High gloss",
    },
    tags: ["spray wax", "wax", "protection", "quick detailer"],
    featured: false,
  },
  {
    id: "10",
    slug: "iron-decontamination-spray",
    name: "Iron Decontamination Spray",
    price: 27.95,
    originalPrice: undefined,
    rating: 4.6,
    reviewCount: 68,
    category: "chemicals",
    brand: "Masterwolf",
    sku: "MW-CH-001",
    inStock: true,
    stockCount: 110,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "pH-balanced iron fallout remover that chemically dissolves embedded iron particles and brake dust on paint, glass, and wheels. The vivid colour-change reaction shows you exactly where contamination is being removed.",
    specifications: {
      Volume: "500ml",
      Type: "pH-balanced iron remover",
      Application: "Spray on, dwell, rinse",
      "Dwell Time": "3–5 minutes",
      "Colour Change": "Yes – purple reaction",
      "pH Level": "Neutral (6.5–7.5)",
    },
    tags: ["iron remover", "decontamination", "fallout remover", "paint prep"],
    featured: false,
  },
  {
    id: "11",
    slug: "foam-lance-attachment",
    name: "Foam Lance Attachment",
    price: 89.95,
    originalPrice: 109.95,
    rating: 4.7,
    reviewCount: 95,
    category: "equipment",
    brand: "Masterwolf",
    sku: "MW-EQ-001",
    inStock: true,
    stockCount: 44,
    images: [
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&q=80",
    ],
    description:
      "Heavy-duty foam lance with adjustable foam ratio and fan pattern for full-vehicle coverage. Compatible with most pressure washers, delivering thick, clinging foam that lifts dirt safely before contact washing.",
    specifications: {
      Fitting: "1/4\" quick-connect (universal)",
      "Bottle Capacity": "1 litre",
      "Adjustable Nozzle": "Yes – fan pattern",
      "Foam Ratio": "Adjustable knob",
      "Pressure Range": "100–250 bar",
      Material: "Stainless steel + polycarbonate bottle",
    },
    tags: ["foam lance", "pressure washer", "snow foam", "pre-wash"],
    featured: false,
  },
  {
    id: "12",
    slug: "professional-detailing-kit-bundle",
    name: "Professional Detailing Kit Bundle",
    price: 199.0,
    originalPrice: 279.0,
    rating: 4.9,
    reviewCount: 183,
    category: "bundles",
    brand: "Masterwolf",
    sku: "MW-BN-001",
    inStock: true,
    stockCount: 27,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
    ],
    description:
      "Everything a professional detailer needs in one complete kit. Includes cutting and finishing pads, microfibre cloths, heavy cut compound, fine polish, detailing spray wax, and a premium carry bag. Save over 28% compared to buying individually.",
    specifications: {
      "Cutting Foam Pad": "1× 150mm",
      "Finishing Foam Pad": "1× 150mm",
      "Microfibre Cloths": "5× 400gsm",
      "Heavy Cut Compound": "500ml",
      "Fine Polish": "500ml",
      "Spray Wax": "500ml",
      "Carry Bag": "Included",
    },
    tags: ["bundle", "kit", "complete set", "starter kit", "professional"],
    featured: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}
